apiVersion : apps/v1
kind: Deployment
metadata:
  name: spring 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring 
    spec:
      containers:
        - name: spring 
          image: cicdimagenesupsf.azurecr.io/spring
          ports:
          - containerPort: 80